// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using TransitInfoAPI.Data;

#nullable disable

namespace TransitInfoAPI.Migrations
{
    [DbContext(typeof(TransitDbContext))]
    [Migration("20260615193301_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TransitInfoAPI.Entities.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgencyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FareUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeedVersionId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Timezone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FeedVersionId");

                    b.HasIndex("OperatorId");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActivePeriodEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActivePeriodStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("AffectedAgencyIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AffectedRouteIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AffectedStopIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AffectedTripIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Effect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeedId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HeaderText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FeedId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("FeedVersionId")
                        .HasColumnType("int");

                    b.Property<bool>("Friday")
                        .HasColumnType("bit");

                    b.Property<bool>("Monday")
                        .HasColumnType("bit");

                    b.Property<bool>("Saturday")
                        .HasColumnType("bit");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<bool>("Sunday")
                        .HasColumnType("bit");

                    b.Property<bool>("Thursday")
                        .HasColumnType("bit");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("bit");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FeedVersionId");

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.CalendarDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("ExceptionType")
                        .HasColumnType("int");

                    b.Property<int>("FeedVersionId")
                        .HasColumnType("int");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FeedVersionId");

                    b.ToTable("CalendarDates");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.CanonicalRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Geometry>("Geometry")
                        .HasColumnType("geography");

                    b.Property<string>("GlobalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnestopId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<string>("RouteType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupersedesIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextColor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OnestopId")
                        .IsUnique();

                    b.HasIndex("OperatorId");

                    b.ToTable("CanonicalRoutes");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.CanonicalStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdmCountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdmRegionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Point>("Geometry")
                        .HasColumnType("geography");

                    b.Property<string>("GlobalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnestopId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ParentStationId")
                        .HasColumnType("int");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryRouteType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupersedesIds")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("OnestopId")
                        .IsUnique();

                    b.HasIndex("ParentStationId");

                    b.HasIndex("PlaceId");

                    b.ToTable("CanonicalStations");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.CanonicalStationOperator", b =>
                {
                    b.Property<int>("CanonicalStationId")
                        .HasColumnType("int");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<string>("PlatformInfo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CanonicalStationId", "OperatorId");

                    b.HasIndex("OperatorId");

                    b.ToTable("CanonicalStationOperators");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Feed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("LicenseCommercialUseAllowed")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("LicenseRedistributionAllowed")
                        .HasColumnType("bit");

                    b.Property<bool?>("LicenseShareAlikeOptional")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnestopId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.Property<int>("RefreshIntervalSeconds")
                        .HasColumnType("int");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupersedesIds")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("Feeds");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.FeedVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgencyCount")
                        .HasColumnType("int");

                    b.Property<Geometry>("ConvexHull")
                        .HasColumnType("geography");

                    b.Property<int>("FeedId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImportError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImportStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RouteCount")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("ServiceLevelEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ServiceLevelStart")
                        .HasColumnType("date");

                    b.Property<string>("Sha1")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("StopCount")
                        .HasColumnType("int");

                    b.Property<int>("TripCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Sha1");

                    b.HasIndex("FeedId", "IsActive");

                    b.ToTable("FeedVersions");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.MobilityProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConverterConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OperatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("MobilityProviders");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.MobilityStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvailableVehicles")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("MobilityProviderId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("MobilityProviderId");

                    b.ToTable("MobilityStations");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssociatedFeeds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GlobalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OnestopId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OperatorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupersedesIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WikidataId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("OnestopId")
                        .IsUnique();

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdmCountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdmRegionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Population")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.RawStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CanonicalStationId")
                        .HasColumnType("int");

                    b.Property<int>("FeedVersionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lon")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentRawStopId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlatformCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawStopId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReconciliationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("WheelchairBoarding")
                        .HasColumnType("bit");

                    b.Property<string>("ZoneId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalStationId");

                    b.HasIndex("FeedVersionId", "RawStopId");

                    b.ToTable("RawStops");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.ReconciliationCandidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoReconciled")
                        .HasColumnType("bit");

                    b.Property<string>("CanonicalRouteType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DistanceMatched")
                        .HasColumnType("bit");

                    b.Property<decimal>("DistanceMeters")
                        .HasPrecision(14, 4)
                        .HasColumnType("decimal(14,4)");

                    b.Property<int>("FeedId")
                        .HasColumnType("int");

                    b.Property<bool>("NameMatched")
                        .HasColumnType("bit");

                    b.Property<decimal>("NameSimilarityScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("RawRouteType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RawStopId")
                        .HasColumnType("int");

                    b.Property<double>("RawStopLat")
                        .HasColumnType("float");

                    b.Property<double>("RawStopLon")
                        .HasColumnType("float");

                    b.Property<string>("RawStopName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedByAdminId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RouteTypeMatched")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SuggestedCanonicalStationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FeedId");

                    b.HasIndex("RawStopId");

                    b.HasIndex("SuggestedCanonicalStationId");

                    b.ToTable("ReconciliationCandidates");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Shape", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FeedVersionId")
                        .HasColumnType("int");

                    b.Property<LineString>("Geometry")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.Property<string>("ShapeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FeedVersionId");

                    b.ToTable("Shapes");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.StopTime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArrivalTime")
                        .HasColumnType("int");

                    b.Property<int?>("CanonicalStationId")
                        .HasColumnType("int");

                    b.Property<int>("DepartureTime")
                        .HasColumnType("int");

                    b.Property<int?>("DropOffType")
                        .HasColumnType("int");

                    b.Property<int?>("PickupType")
                        .HasColumnType("int");

                    b.Property<string>("RawStopId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StopHeadsign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StopSequence")
                        .HasColumnType("int");

                    b.Property<bool?>("Timepoint")
                        .HasColumnType("bit");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalStationId");

                    b.HasIndex("TripId");

                    b.ToTable("StopTimes");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("BikesAllowed")
                        .HasColumnType("bit");

                    b.Property<int?>("CanonicalRouteId")
                        .HasColumnType("int");

                    b.Property<int?>("DirectionId")
                        .HasColumnType("int");

                    b.Property<int>("FeedVersionId")
                        .HasColumnType("int");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShapeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TripHeadsign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TripShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("WheelchairAccessible")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalRouteId");

                    b.HasIndex("FeedVersionId", "TripId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Agency", b =>
                {
                    b.HasOne("TransitInfoAPI.Entities.FeedVersion", "FeedVersion")
                        .WithMany("Agencies")
                        .HasForeignKey("FeedVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransitInfoAPI.Entities.Operator", "Operator")
                        .WithMany("Agencies")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FeedVersion");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Alert", b =>
                {
                    b.HasOne("TransitInfoAPI.Entities.Feed", "Feed")
                        .WithMany()
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Calendar", b =>
                {
                    b.HasOne("TransitInfoAPI.Entities.FeedVersion", "FeedVersion")
                        .WithMany()
                        .HasForeignKey("FeedVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FeedVersion");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.CalendarDate", b =>
                {
                    b.HasOne("TransitInfoAPI.Entities.FeedVersion", "FeedVersion")
                        .WithMany()
                        .HasForeignKey("FeedVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FeedVersion");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.CanonicalRoute", b =>
                {
                    b.HasOne("TransitInfoAPI.Entities.Operator", "Operator")
                        .WithMany("Routes")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.CanonicalStation", b =>
                {
                    b.HasOne("TransitInfoAPI.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransitInfoAPI.Entities.Country", "Country")
                        .WithMany("CanonicalStations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransitInfoAPI.Entities.CanonicalStation", "ParentStation")
                        .WithMany("ChildStations")
                        .HasForeignKey("ParentStationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransitInfoAPI.Entities.Place", "Place")
                        .WithMany("Stations")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("ParentStation");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.CanonicalStationOperator", b =>
                {
                    b.HasOne("TransitInfoAPI.Entities.CanonicalStation", "CanonicalStation")
                        .WithMany("StationOperators")
                        .HasForeignKey("CanonicalStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransitInfoAPI.Entities.Operator", "Operator")
                        .WithMany("StationOperators")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanonicalStation");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.City", b =>
                {
                    b.HasOne("TransitInfoAPI.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Feed", b =>
                {
                    b.HasOne("TransitInfoAPI.Entities.Operator", "Operator")
                        .WithMany("Feeds")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.FeedVersion", b =>
                {
                    b.HasOne("TransitInfoAPI.Entities.Feed", "Feed")
                        .WithMany("FeedVersions")
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feed");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.MobilityProvider", b =>
                {
                    b.HasOne("TransitInfoAPI.Entities.Operator", "Operator")
                        .WithMany("MobilityProviders")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.MobilityStation", b =>
                {
                    b.HasOne("TransitInfoAPI.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransitInfoAPI.Entities.Country", "Country")
                        .WithMany("MobilityStations")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransitInfoAPI.Entities.MobilityProvider", "MobilityProvider")
                        .WithMany()
                        .HasForeignKey("MobilityProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Country");

                    b.Navigation("MobilityProvider");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Operator", b =>
                {
                    b.HasOne("TransitInfoAPI.Entities.Country", "Country")
                        .WithMany("Operators")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.RawStop", b =>
                {
                    b.HasOne("TransitInfoAPI.Entities.CanonicalStation", "CanonicalStation")
                        .WithMany("RawStops")
                        .HasForeignKey("CanonicalStationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransitInfoAPI.Entities.FeedVersion", "FeedVersion")
                        .WithMany("RawStops")
                        .HasForeignKey("FeedVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanonicalStation");

                    b.Navigation("FeedVersion");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.ReconciliationCandidate", b =>
                {
                    b.HasOne("TransitInfoAPI.Entities.Feed", "Feed")
                        .WithMany()
                        .HasForeignKey("FeedId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransitInfoAPI.Entities.RawStop", "RawStop")
                        .WithMany()
                        .HasForeignKey("RawStopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TransitInfoAPI.Entities.CanonicalStation", "SuggestedCanonicalStation")
                        .WithMany()
                        .HasForeignKey("SuggestedCanonicalStationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Feed");

                    b.Navigation("RawStop");

                    b.Navigation("SuggestedCanonicalStation");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Region", b =>
                {
                    b.HasOne("TransitInfoAPI.Entities.Country", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Shape", b =>
                {
                    b.HasOne("TransitInfoAPI.Entities.FeedVersion", "FeedVersion")
                        .WithMany()
                        .HasForeignKey("FeedVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FeedVersion");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.StopTime", b =>
                {
                    b.HasOne("TransitInfoAPI.Entities.CanonicalStation", "CanonicalStation")
                        .WithMany()
                        .HasForeignKey("CanonicalStationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransitInfoAPI.Entities.Trip", "Trip")
                        .WithMany("StopTimes")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanonicalStation");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Trip", b =>
                {
                    b.HasOne("TransitInfoAPI.Entities.CanonicalRoute", "CanonicalRoute")
                        .WithMany()
                        .HasForeignKey("CanonicalRouteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TransitInfoAPI.Entities.FeedVersion", "FeedVersion")
                        .WithMany()
                        .HasForeignKey("FeedVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CanonicalRoute");

                    b.Navigation("FeedVersion");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.CanonicalStation", b =>
                {
                    b.Navigation("ChildStations");

                    b.Navigation("RawStops");

                    b.Navigation("StationOperators");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Country", b =>
                {
                    b.Navigation("CanonicalStations");

                    b.Navigation("Cities");

                    b.Navigation("MobilityStations");

                    b.Navigation("Operators");

                    b.Navigation("Regions");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Feed", b =>
                {
                    b.Navigation("FeedVersions");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.FeedVersion", b =>
                {
                    b.Navigation("Agencies");

                    b.Navigation("RawStops");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Operator", b =>
                {
                    b.Navigation("Agencies");

                    b.Navigation("Feeds");

                    b.Navigation("MobilityProviders");

                    b.Navigation("Routes");

                    b.Navigation("StationOperators");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Place", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("TransitInfoAPI.Entities.Trip", b =>
                {
                    b.Navigation("StopTimes");
                });
#pragma warning restore 612, 618
        }
    }
}
